# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postTypeId',
            field=models.IntegerField(choices=[(1, b'Question'), (2, b'Answer')], default=2),
        ),
        migrations.AlterField(
            model_name='vote',
            name='BountyAmount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='userId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dataHandler.User'),
        ),
    ]
