# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0002_auto_20160407_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='acceptedAnswerId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='main_answer', to='dataHandler.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='answerCount',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='closedDate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='commentCount',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='communityOwnedDate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='creationDate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='favoriteCount',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='lastActivityDate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='lastEditDate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='lastEditorDisplayName',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='lastEditorUserId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='last_editor', to='dataHandler.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ownerUserId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='dataHandler.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='base_question', to='dataHandler.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='post',
            name='viewCount',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='aboutMe',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='creationDate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='displayName',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='downVotes',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='emailHash',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastAccessDate',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(default=None, max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='reputation',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='upVotes',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='webSiteURL',
            field=models.URLField(default=None),
        ),
    ]
