# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0004_auto_20160407_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='lastEditorUserId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_editor', to='dataHandler.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ownerUserId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='dataHandler.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_question', to='dataHandler.Post'),
        ),
    ]
