# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0006_auto_20160407_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='userId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataHandler.User'),
        ),
    ]
