# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0008_auto_20160407_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parentId',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_question', to='dataHandler.Post'),
        ),
    ]
