# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0009_post_parentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deletionDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
