# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0010_post_deletiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='views',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
