# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0011_user_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accountId',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
