# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandler', '0012_user_accountid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userDisplayName',
            field=models.CharField(default='Unknown', max_length=1024),
            preserve_default=False,
        ),
    ]
